### ISSUE TITLE
Problem overwriting index of store

### ISSUE THREAD

**Issue by wolfgangdie** [talpor/react-context-manager-cli#3]
#### Environment

Windows 10 x64 1909
Node v13.11.0
Yarn v1.22.4
react-context-manager-cli v0.0.6

#### Description

After successfully created a new sub-store, the overwriting process for the index of store fails with the next message:

```shell
? Do you want to overwrite your index of your Store? Yes
(node:3800) UnhandledPromiseRejectionWarning: SyntaxError: ',' expected. (7:25)
   5 |           import { authStore, IAuthStore } from './auth/store';
   6 |           import { authActions, IAuthActions } from './auth/actions';
>  7 |           import { mocks.tsStore, IMocks.tsStore } from './mocks.ts/store';
     |                         ^
   8 |           import { mocks.tsActions, IMocks.tsActions } from './mocks.ts/actions';
   9 |           import { reactionStore, IReactionStore } from './reaction/store';
  10 |           import { reactionActions, IReactionActions } from './reaction/actions';
    at t (C:\Users\Wolfgang\AppData\Local\Yarn\Data\global\node_modules\prettier\parser-typescript.js:1:285)
    at Object.parse (C:\Users\Wolfgang\AppData\Local\Yarn\Data\global\node_modules\prettier\parser-typescript.js:14:180461)
    at Object.parse (C:\Users\Wolfgang\AppData\Local\Yarn\Data\global\node_modules\prettier\index.js:9739:19)
    at coreFormat (C:\Users\Wolfgang\AppData\Local\Yarn\Data\global\node_modules\prettier\index.js:13252:23)
    at format (C:\Users\Wolfgang\AppData\Local\Yarn\Data\global\node_modules\prettier\index.js:13510:73)
    at formatWithCursor (C:\Users\Wolfgang\AppData\Local\Yarn\Data\global\node_modules\prettier\index.js:13526:12)
    at C:\Users\Wolfgang\AppData\Local\Yarn\Data\global\node_modules\prettier\index.js:44207:15
    at Proxy.format (C:\Users\Wolfgang\AppData\Local\Yarn\Data\global\node_modules\prettier\index.js:44226:12)
    at C:\Users\Wolfgang\AppData\Local\Yarn\Data\global\node_modules\@talpor\react-context-manager-cli\src\utils\helpers.js:152:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by fergalindez** [comment]
Thanks for reporting the issue @wolfgangdie. We already fixed it in version 0.0.7
